# Site settings
title: Sam's Kitchen
email: sambuckberry@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of Sam Buckberry's recipes.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://sambuckberry.me" # the base hostname & protocol for your site
#twitter_username: sambuckberry
#github_username:  sambuckberry

# Build settings
markdown: kramdown
