# Site settings
title: Sam's Kitchen
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of Sam Buckberry's recipes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: sambuckberry
github_username:  sambuckberry

# Build settings
markdown: kramdown
