# Site settings
title: Projet COMMO | COMMO Project
email: projetcommotion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ce site est dédié au projet de recherche réalisé par Samuel Guay et son équipe
  qui sont supervisé par le chercheur Louis De Beaumont qui a su développé une expertise
  sur les commotions cérébrales ces 15 dernières années.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: samguay
github_username:  teamTBI

# Build settings
markdown: kramdown
